// This file is auto-generated by @hey-api/openapi-ts

/**
 * BillingAddressCollection
 */
export type BillingAddressCollection = 'auto' | 'required';

/**
 * CaptureMethod
 */
export type CaptureMethod = 'automatic' | 'automatic_async' | 'manual';

/**
 * CheckoutSessionCreateRequest
 */
export type CheckoutSessionCreateRequest = {
    /**
     * Client Reference Id
     * ID
     */
    client_reference_id?: string;
    /**
     * Customer
     * 顧客ID
     */
    customer?: string;
    /**
     * Customer Email
     * 顧客オブジェクトを作成する時に使われます。指定されていない場合、顧客にメールアドレスの入力を求めます。すでに顧客のメールアドレスを持っている場合は、このパラメータを使ってあらかじめ情報を入力しておくことが可能です。支払いが完了した後に顧客情報を取得したい場合は、customer属性を使用します。
     */
    customer_email?: string;
    /**
     * Checkout Session の確定時に Customer を作成するかどうかを指定します。<br>
     * Customer が作成されない場合でも `customer_details` で Checkout に入力されたメールアドレス、住所、その他の顧客データを取得できます。<br>
     * Customer を作成しない Session は、ダッシュボードでゲスト顧客としてグループ化されます。<br>
     * `payment` および `setup` モードでのみ設定可能です。
     */
    customer_creation?: CustomerCreation;
    /**
     * Line Items
     * 顧客が購入する商品のリストです。このパラメータを使用して、1回限りまたは定期的な料金を渡します。
     *
     * `payment` モードの場合、最大100個のラインアイテムを使用できます。
     * <!-- `subscription` モードの場合、定期的な料金のラインアイテムは最大20個、1回限りの料金のラインアイテムは最大20個です。1回限りの料金のラインアイテムは、最初の請求書にのみ記載されます。 -->
     *
     */
    line_items?: Array<LineItemRequest>;
    /**
     * Checkout Session のモード
     *
     * | 指定できる値 |
     * |:---|
     * | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     */
    mode: CheckoutSessionMode;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Return Url
     * 顧客が支払いを行うか、支払いをキャンセルした後にリダイレクトする URL です。
     */
    return_url?: string;
    /**
     * Success Url
     * 支払いや設定が完了した際に、PAY.JP が顧客をリダイレクトするURL。成功したCheckout Sessionからの情報をページで使用したい場合は、成功ページのカスタマイズに関するガイドをお読みください。
     */
    success_url?: string;
    /**
     * Cancel Url
     * キャンセル時のリダイレクトURL
     */
    cancel_url?: string;
    /**
     * Checkout で顧客の請求先住所を収集するかどうかを指定します。デフォルトは `auto` です。
     *
     * | 指定できる値 |
     * |:---|
     * | **auto**: 請求先住所が必要と判断した場合に入力欄が表示されます。 |
     * | **required**: 常に請求先住所の入力欄が表示されまうs。 |
     *
     */
    billing_address_collection?: BillingAddressCollection;
    /**
     * 価格の通貨。現在は `jpy` のみサポートしています。
     */
    currency?: Currency;
    /**
     * Expires At
     * Checkout Session の有効期限が失効する日時。
     */
    expires_at?: string;
    /**
     * Checkout 画面の表示言語を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **ja**: 日本語で表示します。 |
     *
     */
    locale?: Locale;
    /**
     * `payment` モード指定時に PaymentIntent 作成に使用するパラメーター。
     */
    payment_intent_data?: PaymentIntentDataRequest;
    /**
     * この PaymentIntent の支払い方法の個別設定。
     */
    payment_method_options?: PaymentMethodOptionsRequest;
    /**
     * Payment Method Types
     * この PaymentIntent で使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合、ダッシュボードで利用可能な状態にしている支払い方法を自動的に表示します。
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * `setup` モードの Checkout Session を作成する際、SetupIntent の作成に渡されるパラメーター
     */
    setup_intent_data?: SetupIntentDataRequest;
    /**
     * Checkout の画面上に表示される送信ボタンなど、ページ上の関連テキストをカスタマイズするために使用されます。<br>
     * `submit_type` は、`payment` モードの Checkout Session でのみ指定できます。未指定時、あるいは `auto` の場合、`pay` が使用されます。
     *
     * | 指定できる値 |
     * |:---|
     * | **auto**: `pay` が使用されます。 |
     * | **pay**: 「支払う」（デフォルト） |
     * | **book**: 「予約する」 |
     * | **donate**: 「寄付する」 |
     *
     */
    submit_type?: CheckoutSessionSubmitType;
    /**
     * Checkout Session の UI モード。デフォルトは `hosted` です。<br>
     *
     * | 指定できる値 |
     * |:---|
     * | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     */
    ui_mode?: CheckoutSessionUiMode;
};

/**
 * CheckoutSessionDetailsResponse
 */
export type CheckoutSessionDetailsResponse = {
    /**
     * Id
     * ID
     */
    id?: string;
    /**
     * Object
     */
    object?: 'checkout.session';
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode?: boolean;
    /**
     * Amount Subtotal
     * 割引や税金が適用される前のすべての商品の合計金額
     */
    amount_subtotal?: number | null;
    /**
     * Amount Total
     * 割引と税金が適用された後のすべての商品の合計金額
     */
    amount_total?: number | null;
    /**
     * Checkout で顧客の請求先住所を収集するかどうかを指定します。デフォルトは `auto` です。
     *
     * | 指定できる値 |
     * |:---|
     * | **auto**: 請求先住所が必要と判断した場合に入力欄が表示されます。 |
     * | **required**: 常に請求先住所の入力欄が表示されまうs。 |
     *
     */
    billing_address_collection?: BillingAddressCollection | null;
    /**
     * Cancel Url
     * キャンセル時のリダイレクトURL
     */
    cancel_url?: string | null;
    /**
     * Customer
     * 顧客ID
     */
    customer?: string | CustomerResponse | null;
    /**
     * Customer Email
     * 顧客オブジェクトを作成する時に使われます。指定されていない場合、顧客にメールアドレスの入力を求めます。すでに顧客のメールアドレスを持っている場合は、このパラメータを使ってあらかじめ情報を入力しておくことが可能です。支払いが完了した後に顧客情報を取得したい場合は、customer属性を使用します。
     */
    customer_email?: string | null;
    /**
     * Customer Details
     * `expand` パラメーターを指定した場合、顧客の詳細情報を含んだオブジェクトが返却されます。
     *
     * | 説明 |
     * |:---|
     * | **email**: 顧客のメールアドレス |
     *
     */
    customer_details?: {
        [key: string]: unknown;
    };
    /**
     * Expires At
     * Checkout Session の有効期限が失効する日時。
     */
    expires_at?: string | null;
    /**
     * 価格の通貨。現在は `jpy` のみサポートしています。
     */
    currency?: Currency;
    /**
     * Checkout 画面の表示言語を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **ja**: 日本語で表示します。 |
     *
     */
    locale?: Locale | null;
    /**
     * Payment Intent
     * `payment` モードの Checkout Session の PaymentIntent の ID。PaymentIntent を確定 (confirm)、またはキャンセルすることはできません。キャンセルするには、代わりに Checkout Session を期限切れにしてください。
     */
    payment_intent?: string | {
        [key: string]: unknown;
    } | null;
    /**
     * Payment Method Types
     * この PaymentIntent で使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合、ダッシュボードで利用可能な状態にしている支払い方法を自動的に表示します。
     */
    payment_method_types?: Array<PaymentMethodTypes> | null;
    /**
     * Payment Method Options
     * この PaymentIntent の支払い方法の個別設定。
     */
    payment_method_options?: {
        [key: string]: unknown;
    } | null;
    /**
     * `setup` モードの Checkout Session の SetupIntent の ID。Checkout Session の SetupIntent を確定 (confirm)、またはキャンセルすることはできません。キャンセルするには、代わりに Checkout Session を期限切れにしてください。
     */
    setup_intent?: PaymentIntentDataRequest | null;
    /**
     * Checkout の画面上に表示される送信ボタンなど、ページ上の関連テキストをカスタマイズするために使用されます。<br>
     * `submit_type` は、`payment` モードの Checkout Session でのみ指定できます。未指定時、あるいは `auto` の場合、`pay` が使用されます。
     *
     * | 指定できる値 |
     * |:---|
     * | **auto**: `pay` が使用されます。 |
     * | **pay**: 「支払う」（デフォルト） |
     * | **book**: 「予約する」 |
     * | **donate**: 「寄付する」 |
     *
     */
    submit_type?: CheckoutSessionSubmitType | null;
    /**
     * Checkout Session のモード
     *
     * | 指定できる値 |
     * |:---|
     * | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     */
    mode?: CheckoutSessionMode;
    /**
     * Checkout Session の UI モード。デフォルトは `hosted` です。<br>
     *
     * | 指定できる値 |
     * |:---|
     * | **hosted**: PAY.JPでホスティングしている画面を使用します。 |
     *
     */
    ui_mode?: CheckoutSessionUiMode;
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at?: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at?: string;
    /**
     * 顧客が購入する商品のリストです。このパラメータを使用して、1回限りまたは定期的な料金を渡します。
     *
     * `payment` モードの場合、最大100個のラインアイテムを使用できます。
     * <!-- `subscription` モードの場合、定期的な料金のラインアイテムは最大20個、1回限りの料金のラインアイテムは最大20個です。1回限りの料金のラインアイテムは、最初の請求書にのみ記載されます。 -->
     *
     */
    line_items?: CheckoutSessionLineItemsResponse | null;
    /**
     * Success Url
     * 支払いや設定が完了した際に、PAY.JP が顧客をリダイレクトするURL。成功したCheckout Sessionからの情報をページで使用したい場合は、成功ページのカスタマイズに関するガイドをお読みください。
     */
    success_url?: string | null;
    /**
     * Url
     * URL
     */
    url?: string;
};

/**
 * CheckoutSessionLineItemDataResponse
 */
export type CheckoutSessionLineItemDataResponse = {
    /**
     * Object
     */
    object?: 'line_item';
    /**
     * Id
     * ID
     */
    id?: string;
    /**
     * Amount Subtotal
     * 割引や税金が適用される前のすべての商品の合計金額
     */
    amount_subtotal?: number;
    /**
     * Amount Tax
     * 税額
     */
    amount_tax?: number;
    /**
     * Amount Total
     * 割引と税金が適用された後のすべての商品の合計金額
     */
    amount_total?: number;
    /**
     * 価格の通貨。現在は `jpy` のみサポートしています。
     */
    currency?: Currency;
    /**
     * Description
     * 説明
     */
    description?: string;
    /**
     * 料金情報
     */
    price?: CheckoutSessionLineItemPriceResponse;
    /**
     * Quantity
     * 数量
     */
    quantity?: number;
};

/**
 * CheckoutSessionLineItemPriceResponse
 */
export type CheckoutSessionLineItemPriceResponse = {
    /**
     * Id
     * 料金ID
     */
    id?: string;
    /**
     * Object
     */
    object?: 'price';
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode?: boolean;
    /**
     * Active
     * 有効かどうか
     */
    active?: boolean;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Nickname
     * ニックネーム
     */
    nickname?: string | null;
    /**
     * 料金の種類
     */
    type?: PriceType;
    /**
     * Lookup Key
     * 検索キー
     */
    lookup_key?: string | null;
    /**
     * 通貨
     */
    currency?: Currency;
    /**
     * Product
     * 商品ID
     */
    product?: string;
    /**
     * Unit Amount
     * 単価
     */
    unit_amount?: number;
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at?: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at?: string;
};

/**
 * CheckoutSessionLineItemsResponse
 */
export type CheckoutSessionLineItemsResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     * データ
     */
    data?: Array<CheckoutSessionLineItemDataResponse>;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more?: boolean;
    /**
     * Url
     * URL
     */
    url?: string;
};

/**
 * CheckoutSessionListResponse
 */
export type CheckoutSessionListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<CheckoutSessionDetailsResponse>;
};

/**
 * CheckoutSessionMode
 */
export type CheckoutSessionMode = 'payment' | 'setup';

/**
 * CheckoutSessionSubmitType
 */
export type CheckoutSessionSubmitType = 'auto' | 'book' | 'donate' | 'pay';

/**
 * CheckoutSessionUIMode
 */
export type CheckoutSessionUiMode = 'hosted';

/**
 * CheckoutSessionUpdateRequest
 */
export type CheckoutSessionUpdateRequest = {
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * Country
 */
export type Country = 'JP';

/**
 * Currency
 */
export type Currency = 'jpy';

/**
 * CustomerCreateRequest
 */
export type CustomerCreateRequest = {
    /**
     * Email
     * 顧客のメールアドレス。メールアドレスの形式が正しいかどうかは検証されます。
     */
    email?: string;
    /**
     * Description
     * 顧客オブジェクトに付加できる任意の文字列です。これは、ダッシュボードで顧客と一緒に表示されます。
     */
    description?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Id
     * 顧客ID。100桁までの一意な文字列を指定できます。使える文字は半角英数字、ハイフン(-)、アンダースコア(_)です。未指定時は `cus_` で始まる32桁までの一意な文字列が自動生成されます。
     */
    id?: string;
};

/**
 * CustomerCreation
 */
export type CustomerCreation = 'always' | 'if_required';

/**
 * CustomerListResponse
 */
export type CustomerListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<CustomerResponse>;
};

/**
 * CustomerResponse
 */
export type CustomerResponse = {
    /**
     * Id
     * 顧客ID
     */
    id?: string;
    /**
     * Object
     */
    object?: 'customer';
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Email
     * メールアドレス
     */
    email: string | null;
    /**
     * Description
     * 顧客の説明
     */
    description: string | null;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
};

/**
 * CustomerUpdateRequest
 */
export type CustomerUpdateRequest = {
    /**
     * Email
     * 顧客のメールアドレス。メールアドレスの形式が正しいかどうかは検証されます。
     */
    email?: string;
    /**
     * Description
     * 顧客オブジェクトに付加できる任意の文字列です。これは、ダッシュボードで顧客と一緒に表示されます。
     */
    description?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: number;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Instance
     */
    instance?: string | null;
    /**
     * Errors
     */
    errors?: Array<{
        [key: string]: string;
    }> | null;
};

/**
 * EventListResponse
 */
export type EventListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     * イベントリスト
     */
    data: Array<EventResponse>;
};

/**
 * EventResponse
 */
export type EventResponse = {
    /**
     * Id
     * イベントID
     */
    id: string;
    /**
     * Object
     */
    object?: 'event';
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Type
     * イベントの種類
     */
    type: string;
    /**
     * Pending Webhooks
     * 設定されたURLへの通知が完了していない(2xxのレスポンスが得られていない)webhookの数
     */
    pending_webhooks: number;
    /**
     * Data
     * このイベントに関連したリソースオブジェクト
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * LineItemAdjustableQuantityRequest
 */
export type LineItemAdjustableQuantityRequest = {
    /**
     * Enabled
     * 数量が任意の 0 以上の整数に調整可能であれば、`true` を指定します。
     */
    enabled?: boolean;
    /**
     * Maximum
     * 顧客が Checkout Session で購入できる最大数量です。デフォルトではこの値は 99 です。999,999 までの値を指定できます。
     */
    maximum?: number;
    /**
     * Minimum
     * 顧客が Checkout Session で購入できる最小数量です。この値はデフォルトで 0 です。
     */
    minimum?: number;
};

/**
 * LineItemRequest
 */
export type LineItemRequest = {
    /**
     * Checkout 画面で顧客がこの商品の購入数量を変更できるようにする。
     */
    adjustable_quantity?: LineItemAdjustableQuantityRequest;
    /**
     * Price
     * 料金ID
     */
    price?: string;
    /**
     * Quantity
     * 購入する商品の数量
     */
    quantity: number;
    /**
     * Tax Rates
     * 税率ID
     */
    tax_rates?: Array<string>;
};

/**
 * Locale
 * IETF language tag (ja, en, ...) or auto
 */
export type Locale = 'auto' | 'ja';

/**
 * PaymentIntentCancelRequest
 */
export type PaymentIntentCancelRequest = {
    /**
     * Cancellation Reason
     * キャンセル理由
     */
    cancellation_reason?: string;
};

/**
 * PaymentIntentCaptureRequest
 */
export type PaymentIntentCaptureRequest = {
    /**
     * Amount To Capture
     * PaymentIntentから確定させる金額は、元の金額以下で指定します。指定されていない場合は、全額（`amount_capturable`）がデフォルトになります。
     */
    amount_to_capture?: number;
};

/**
 * PaymentIntentConfirmRequest
 */
export type PaymentIntentConfirmRequest = {
    /**
     * Payment Method
     * 支払い方法ID
     */
    payment_method?: string;
    /**
     * 指定した場合、PaymentMethodの作成に使用されます。新しいPaymentMethodは、PaymentIntentのpayment_methodプロパティに表示されます。
     */
    payment_method_data?: PaymentMethodCreateRequest;
    /**
     * このPaymentIntentに固有の支払い方法の設定
     */
    payment_method_options?: PaymentMethodOptionsRequest;
    /**
     * Payment Method Types
     * このPaymentIntentで使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合は、PAY.JPは支払い方法の設定から利用可能な支払い方法を動的に表示します。
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * Receipt Email
     * 請求書の送信先メールアドレス。ライブモードで支払いに対して `receipt_email` を指定すると、メール設定に関係なく領収書が送信されます。
     */
    receipt_email?: string;
    /**
     * Return Url
     * 顧客が支払いを完了後かキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=trueの場合のみ指定できます。
     */
    return_url?: string;
    /**
     * Description
     * オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     */
    description?: string;
    /**
     * 支払いの確定方法を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **automatic**: 顧客が支払いを承認すると、自動的に確定させます。 |
     * | **automatic_async**: (デフォルト) 顧客が支払いを承認すると、非同期的に確定させます。レイテンシが改善されるため、capture_method=automaticよりも推奨されます。詳細については、統合ガイドをお読みください。 |
     * | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
     */
    capture_method?: CaptureMethod;
};

/**
 * PaymentIntentCreateRequest
 */
export type PaymentIntentCreateRequest = {
    /**
     * Payment Method
     * 支払い方法ID
     */
    payment_method?: string;
    /**
     * 指定した場合、PaymentMethodの作成に使用されます。新しいPaymentMethodは、PaymentIntentのpayment_methodプロパティに表示されます。
     */
    payment_method_data?: PaymentMethodCreateRequest;
    /**
     * このPaymentIntentに固有の支払い方法の設定
     */
    payment_method_options?: PaymentMethodOptionsRequest;
    /**
     * Payment Method Types
     * このPaymentIntentで使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合は、PAY.JPは支払い方法の設定から利用可能な支払い方法を動的に表示します。
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * Receipt Email
     * 請求書の送信先メールアドレス。ライブモードで支払いに対して `receipt_email` を指定すると、メール設定に関係なく領収書が送信されます。
     */
    receipt_email?: string;
    /**
     * Return Url
     * 顧客が支払いを完了後かキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=trueの場合のみ指定できます。
     */
    return_url?: string;
    /**
     * Description
     * オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     */
    description?: string;
    /**
     * Amount
     * 支払い予定の金額。50円以上9,999,999円以下である必要があります。支払い手段によって上限金額は異なります。
     */
    amount: number;
    /**
     * Customer
     * このPaymentIntentに属する顧客のID（存在する場合）。この顧客以外にすでに紐づけられている支払い方法はこのPaymentIntentでは使用できません。
     */
    customer?: string;
    /**
     * Confirm
     * 「true」に設定すると、このPaymentIntentを直ちに確定しようと試みます。このパラメーターのデフォルトは「false」です。
     */
    confirm?: boolean;
    /**
     * 支払いの確定方法を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **automatic**: 顧客が支払いを承認すると、自動的に確定させます。 |
     * | **automatic_async**: (デフォルト) 顧客が支払いを承認すると、非同期的に確定させます。レイテンシが改善されるため、capture_method=automaticよりも推奨されます。詳細については、統合ガイドをお読みください。 |
     * | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
     */
    capture_method?: CaptureMethod;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * このPaymentIntentの支払い方法で将来の支払いを行う意図があることを示します。<br><br>PaymentIntent に Customer を指定した場合、このパラメータを使って PaymentIntent を確定できます。その後、顧客が必要な操作を完了すると、支払い方法を Customer に紐付けることが可能です。また、Customer を指定しない場合でも、取引が完了した後に支払い方法を Customer に紐付けることはできます。
     */
    setup_future_usage?: Usage;
};

/**
 * PaymentIntentDataRequest
 */
export type PaymentIntentDataRequest = {
    /**
     * 支払いの確定方法を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **automatic**: 顧客が支払いを承認すると自動的に確定します。 |
     * | **automatic_async**: (デフォルト) 顧客が支払いを承認すると、非同期で確定させます。レイテンシが改善されるため、`capture_method=automatic` よりも推奨されます。詳細については、統合ガイドをお読みください。 |
     * | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
     */
    capture_method?: CaptureMethod;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Setup Future Usage
     * この PaymentIntent に設定されている支払い方法で今後決済を行うかの設定です。<br><br>
     * PaymentIntent に Customer を指定した場合、このパラメータを使って PaymentIntent を確定できます。
     * その後、顧客が必要な操作を完了すると、支払い方法を Customer に紐付けることが可能です。また、Customer を指定しない場合でも、取引が完了した後に支払い方法を Customer に紐付けることはできます。
     */
    setup_future_usage?: 'off_session' | 'on_session';
};

/**
 * PaymentIntentIncrementAuthorizationRequest
 */
export type PaymentIntentIncrementAuthorizationRequest = {
    /**
     * Amount
     * 支払い予定の金額。50円以上9,999,999円以下である必要があります。支払い手段によって上限金額は異なります。
     */
    amount: number;
    /**
     * Description
     * オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     */
    description?: string;
};

/**
 * PaymentIntentListResponse
 */
export type PaymentIntentListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     * 支払いインテントリスト
     */
    data: Array<PaymentIntentResponse>;
};

/**
 * PaymentIntentResponse
 */
export type PaymentIntentResponse = {
    /**
     * Id
     * 支払いインテントID
     */
    id: string;
    /**
     * Object
     */
    object?: 'payment_intent';
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Amount
     * 支払い予定の金額。50円以上9,999,999円以下である必要があります。支払い手段によって上限金額は異なります。
     */
    amount: number;
    /**
     * Amount Capturable
     * このPaymentIntentの確定可能な金額。
     */
    amount_capturable: number | null;
    /**
     * Amount Received
     * このPaymentIntentの `amount` のうち、確定した金額。
     */
    amount_received: number | null;
    /**
     * Client Secret
     * このPaymentIntentのクライアントシークレットです。フロントエンドで公開APIキーと合わせて使用しPaymentIntentの情報を取得や支払い処理を行います。**この値はこのPaymentIntentの支払いを行う顧客以外へ公開しないでください。**また保存やログへの記録なども行わないでください。
     */
    client_secret: string;
    /**
     * Confirmation Method
     * このPaymentIntentを自動的に確定できるか、あるいは支払いの確定に顧客による操作が必要かを示します。
     *
     * | 指定できる値 |
     * |:---|
     * | **automatic**: PaymentIntentは公開キーを使用して確認できます。next_actionsが処理された後は、支払いを完了するために追加の確認は必要ありません。 |
     * <!-- | **manual**: すべての支払いの確認は秘密鍵を使用して行う必要があります。PaymentIntentは `next_actions` の処理後に `requires_confirmation` 状態に戻り、各支払いはサーバー側で明示的な確認を開始する必要があります。 | -->
     */
    confirmation_method: string | null;
    /**
     * Customer
     * このPaymentIntentに属する顧客のID（存在する場合）。この顧客以外にすでに紐づけられている支払い方法はこのPaymentIntentでは使用できません。
     */
    customer?: string | null;
    /**
     * Description
     * オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     */
    description?: string | null;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Payment Method
     * 支払い方法ID
     */
    payment_method?: string | null;
    /**
     * Payment Method Options
     * このPaymentIntentに固有の支払い方法の設定
     */
    payment_method_options?: {
        [key: string]: unknown;
    } | null;
    /**
     * Payment Method Types
     * このPaymentIntentで使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合は、PAY.JPは支払い方法の設定から利用可能な支払い方法を動的に表示します。
     */
    payment_method_types: Array<string>;
    /**
     * Receipt Email
     * 請求書の送信先メールアドレス。ライブモードで支払いに対して `receipt_email` を指定すると、メール設定に関係なく領収書が送信されます。
     */
    receipt_email?: string | null;
    /**
     * このPaymentIntentのステータスです。<a href="https://docs.pay.jp/v2/payment_intents#status" target="_blank">ステータスの詳細についてはこちらをご覧ください。</a>
     *
     * | 値 |
     * |:---|
     * | **requires_payment_method**: 支払い方法が必要です。 |
     * | **requires_confirmation**: 確認が必要です。 |
     * | **requires_action**: 顧客のアクションが必要です。 |
     * | **processing**: 処理中です。 |
     * | **requires_capture**: 確定が必要です。 |
     * | **canceled**: キャンセルされました。 |
     * | **succeeded**: 成功しました。 |
     */
    status: PaymentIntentStatus;
    /**
     * Next Action
     * プロパティが存在する場合、顧客が支払い設定を続けるために必要な対応が記載されています。
     */
    next_action?: {
        [key: string]: unknown;
    } | null;
    /**
     * Return Url
     * 顧客が支払いを完了後かキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=trueの場合のみ指定できます。
     */
    return_url?: string | null;
    /**
     * 支払いの確定方法を指定します。
     *
     * | 指定できる値 |
     * |:---|
     * | **automatic**: 顧客が支払いを承認すると、自動的に確定させます。 |
     * | **automatic_async**: (デフォルト) 顧客が支払いを承認すると、非同期的に確定させます。レイテンシが改善されるため、capture_method=automaticよりも推奨されます。詳細については、統合ガイドをお読みください。 |
     * | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
     */
    capture_method: CaptureMethod;
};

/**
 * PaymentIntentStatus
 */
export type PaymentIntentStatus = 'canceled' | 'processing' | 'requires_action' | 'requires_capture' | 'requires_confirmation' | 'requires_payment_method' | 'succeeded';

/**
 * PaymentIntentUpdateRequest
 */
export type PaymentIntentUpdateRequest = {
    /**
     * Payment Method
     * 支払い方法ID
     */
    payment_method?: string;
    /**
     * 指定した場合、PaymentMethodの作成に使用されます。新しいPaymentMethodは、PaymentIntentのpayment_methodプロパティに表示されます。
     */
    payment_method_data?: PaymentMethodCreateRequest;
    /**
     * このPaymentIntentに固有の支払い方法の設定
     */
    payment_method_options?: PaymentMethodOptionsRequest;
    /**
     * Payment Method Types
     * このPaymentIntentで使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合は、PAY.JPは支払い方法の設定から利用可能な支払い方法を動的に表示します。
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * Receipt Email
     * 請求書の送信先メールアドレス。ライブモードで支払いに対して `receipt_email` を指定すると、メール設定に関係なく領収書が送信されます。
     */
    receipt_email?: string;
    /**
     * Return Url
     * 顧客が支払いを完了後かキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=trueの場合のみ指定できます。
     */
    return_url?: string;
    /**
     * Description
     * オブジェクトにセットする任意の文字列。ユーザーには表示されません。
     */
    description?: string;
    /**
     * Amount
     * 支払い予定の金額。50円以上9,999,999円以下である必要があります。支払い手段によって上限金額は異なります。
     */
    amount?: number;
    /**
     * Customer
     * このPaymentIntentに属する顧客のID（存在する場合）。この顧客以外にすでに紐づけられている支払い方法はこのPaymentIntentでは使用できません。
     */
    customer?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * PaymentMethodBillingAddressRequest
 */
export type PaymentMethodBillingAddressRequest = {
    /**
     * Country
     * 請求先の住所（国）
     */
    country?: string;
    /**
     * Zip
     * 請求先の住所（郵便番号）
     */
    zip?: string;
    /**
     * State
     * 請求先の住所（都道府県）
     */
    state?: string;
    /**
     * City
     * 請求先の住所（市区町村）
     */
    city?: string;
    /**
     * Line1
     * 請求先の住所（番地など）
     */
    line1?: string;
    /**
     * Line2
     * 請求先の住所（建物名など）
     */
    line2?: string;
};

/**
 * PaymentMethodBillingAddressResponse
 */
export type PaymentMethodBillingAddressResponse = {
    /**
     * Country
     * 請求先の住所（国）
     */
    country: string | null;
    /**
     * Zip
     * 請求先の住所（郵便番号）
     */
    zip: string | null;
    /**
     * State
     * 請求先の住所（都道府県）
     */
    state: string | null;
    /**
     * City
     * 請求先の住所（市区町村）
     */
    city: string | null;
    /**
     * Line1
     * 請求先の住所（番地など）
     */
    line1: string | null;
    /**
     * Line2
     * 請求先の住所（建物名など）
     */
    line2: string | null;
};

/**
 * PaymentMethodBillingDetailsRequest
 */
export type PaymentMethodBillingDetailsRequest = {
    /**
     * Name
     * 請求先の名義
     */
    name?: string;
    /**
     * Phone
     * 請求先の電話番号（ `type=card` の場合、 `phone` または `email` のどちらかは必須）
     */
    phone?: string;
    /**
     * Email
     * 請求先のメールアドレス（ `type=card` の場合、 `phone` または `email` のどちらかは必須）
     */
    email?: string;
    /**
     * 請求先の住所
     */
    address?: PaymentMethodBillingAddressRequest;
};

/**
 * PaymentMethodBillingDetailsResponse
 */
export type PaymentMethodBillingDetailsResponse = {
    /**
     * Name
     * 請求先の名義
     */
    name: string | null;
    /**
     * Phone
     * 請求先の電話番号（ `type=card` の場合、 `phone` または `email` のどちらかは必須）
     */
    phone: string | null;
    /**
     * Email
     * 請求先のメールアドレス（ `type=card` の場合、 `phone` または `email` のどちらかは必須）
     */
    email: string | null;
    /**
     * 請求先の住所
     */
    address: PaymentMethodBillingAddressResponse;
};

/**
 * PaymentMethodCardCreateRequest
 */
export type PaymentMethodCardCreateRequest = {
    /**
     * Customer
     * 顧客ID
     */
    customer?: string;
    /**
     * 請求先情報
     */
    billing_details: PaymentMethodBillingDetailsRequest;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Type
     * クレジットカード決済の場合は `card` を指定します。
     */
    type: 'card';
    /**
     * カード情報
     */
    card: PaymentMethodCreateCardDetailsRequest;
};

/**
 * PaymentMethodCardDetailsResponse
 */
export type PaymentMethodCardDetailsResponse = {
    /**
     * Last4
     * カードの下4桁
     */
    last4: string;
    /**
     * Brand
     * カードのブランド
     */
    brand: string;
    /**
     * Exp Month
     * カードの有効期限（月）
     */
    exp_month: number;
    /**
     * Exp Year
     * カードの有効期限（年）
     */
    exp_year: number;
    /**
     * Fingerprint
     * fingerprint
     */
    fingerprint: string;
    /**
     * Country
     * カードの発行国
     */
    country: string;
};

/**
 * PaymentMethodCardResponse
 */
export type PaymentMethodCardResponse = {
    /**
     * Object
     */
    object?: 'payment_method';
    /**
     * Id
     * ID
     */
    id: string;
    /**
     * Type
     */
    type: 'card';
    /**
     * Customer
     * 顧客ID
     */
    customer?: string | null;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * 請求先情報
     */
    billing_details: PaymentMethodBillingDetailsResponse;
    /**
     * カード情報
     */
    card: PaymentMethodCardDetailsResponse;
};

/**
 * PaymentMethodCardUpdateRequest
 */
export type PaymentMethodCardUpdateRequest = {
    /**
     * Customer
     * 顧客ID
     */
    customer?: string;
    /**
     * 請求先情報
     */
    billing_details?: PaymentMethodBillingDetailsRequest;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Type
     */
    type: 'card';
    /**
     * カード情報
     */
    card: PaymentMethodUpdateCardDetailsRequest;
};

/**
 * PaymentMethodCreateCardDetailsRequest
 */
export type PaymentMethodCreateCardDetailsRequest = {
    /**
     * Number
     * カード番号
     */
    number: string;
    /**
     * Exp Month
     * カードの有効期限（月）
     */
    exp_month: number;
    /**
     * Exp Year
     * カードの有効期限（年）
     */
    exp_year: number;
    /**
     * Cvc
     * カードのセキュリティコード
     */
    cvc: string;
};

/**
 * PaymentMethodCreateRequest
 */
export type PaymentMethodCreateRequest = ({
    type: 'card';
} & PaymentMethodCardCreateRequest) | ({
    type: 'paypay';
} & PaymentMethodPayPayCreateRequest);

/**
 * PaymentMethodListResponse
 */
export type PaymentMethodListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<PaymentMethodResponse>;
};

/**
 * PaymentMethodOptionsCardRequest
 */
export type PaymentMethodOptionsCardRequest = {
    /**
     * Request Extended Authorization
     * オーソリ期間の延長要求。
     *
     * | 指定できる値 |
     * |:---|
     * | **if_available**: オーソリ期間の延長が可能な場合に延長要求を行います。 |
     * | **never**: オーソリ期間の延長要求を行いません。 |
     */
    request_extended_authorization?: 'if_available' | 'never';
    /**
     * Request Three D Secure
     * 3Dセキュア認証の要求方法。
     *
     * | 指定できる値 |
     * |:---|
     * | **any**: 基本的に3Dセキュア認証を要求します。 |
     * | **automatic**: 必要な場合にのみ3Dセキュア認証を要求します。 |
     * <!-- | **challenge**: 3Dセキュア認証を手動で要求します。 | -->
     */
    request_three_d_secure?: 'any' | 'automatic' | 'challenge';
    /**
     * Setup Future Usage
     * セットアップ後の使用方法。
     *
     * | 指定できる値 |
     * |:---|
     * | **off_session**: 顧客がその場にいない状態（例：定期課金や後日請求など）でも決済したい場合に使用します。事前の同意に基づいて自動的に課金されます。 |
     * | **on_session**: 顧客が支払い操作中（例：Web画面で「支払う」ボタンを押す）でのみ決済できればいい場合に指定します。リアルタイムに同意が得られている状態です。 |
     */
    setup_future_usage?: 'off_session' | 'on_session';
};

/**
 * PaymentMethodOptionsRequest
 */
export type PaymentMethodOptionsRequest = {
    /**
     * カード支払い方法に関するオプション
     */
    card: PaymentMethodOptionsCardRequest;
};

/**
 * PaymentMethodPayPayCreateRequest
 */
export type PaymentMethodPayPayCreateRequest = {
    /**
     * Customer
     * 顧客ID
     */
    customer?: string;
    /**
     * 請求先情報
     */
    billing_details?: PaymentMethodBillingDetailsRequest;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Type
     * PayPay決済の場合は `paypay` を指定します。
     */
    type: 'paypay';
};

/**
 * PaymentMethodPayPayResponse
 */
export type PaymentMethodPayPayResponse = {
    /**
     * Object
     */
    object?: 'payment_method';
    /**
     * Id
     * ID
     */
    id: string;
    /**
     * Type
     */
    type: 'paypay';
    /**
     * Customer
     * 顧客ID
     */
    customer?: string | null;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * 請求先情報
     */
    billing_details: PaymentMethodBillingDetailsResponse;
};

/**
 * PaymentMethodResponse
 */
export type PaymentMethodResponse = PaymentMethodCardResponse | PaymentMethodPayPayResponse;

/**
 * PaymentMethodTypes
 */
export type PaymentMethodTypes = 'card' | 'paypay' | 'payid' | 'bank_transfer';

/**
 * PaymentMethodUpdateCardDetailsRequest
 */
export type PaymentMethodUpdateCardDetailsRequest = {
    /**
     * Exp Month
     * カードの有効期限（月）
     */
    exp_month: number;
    /**
     * Exp Year
     * カードの有効期限（年）
     */
    exp_year: number;
};

/**
 * PaymentRefundReason
 */
export type PaymentRefundReason = 'duplicate' | 'fraudulent' | 'requested_by_customer';

/**
 * PaymentRefundStatus
 */
export type PaymentRefundStatus = 'succeeded' | 'failed' | 'pending' | 'canceled' | 'requires_action';

/**
 * PaymentRefundUpdateRequest
 */
export type PaymentRefundUpdateRequest = {
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * PriceCreateRequest
 */
export type PriceCreateRequest = {
    /**
     * Nickname
     * 価格の名称。PAY.JP のダッシュボードで識別するためのもので、顧客には表示されません。
     */
    nickname?: string;
    /**
     * Lookup Key
     * この価格を検索するためのキー。
     */
    lookup_key?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Id
     * 料金ID
     */
    id?: string;
    /**
     * 価格の通貨。現在は `jpy` のみサポートしています。
     */
    currency?: Currency;
    /**
     * Active
     * 価格が有効かどうか。デフォルトは `true`。
     */
    active?: boolean;
    /**
     * Product
     * この価格が紐付く商品のID。
     */
    product?: string;
    /**
     * Unit Amount
     * 価格の単価。0以上の整数となります。
     */
    unit_amount?: number;
};

/**
 * PriceDetailsResponse
 */
export type PriceDetailsResponse = {
    /**
     * Id
     * 料金ID
     */
    id?: string;
    /**
     * Object
     */
    object?: 'price';
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode?: boolean;
    /**
     * Active
     * 価格が有効かどうか。デフォルトは `true`。
     */
    active?: boolean;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Nickname
     * 価格の名称。PAY.JP のダッシュボードで識別するためのもので、顧客には表示されません。
     */
    nickname?: string | null;
    /**
     * 価格が一度限りの購入か、継続的な（サブスクリプション）購入かに応じて、`one_time` または `recurring` のいずれかとなります。
     *
     * | 指定できる値 |
     * |:---|
     * | **one_time**: 1回限りの価格。 |
     * | **recurring**: 継続的な価格。 |
     */
    type?: PriceType;
    /**
     * Lookup Key
     * この価格を検索するためのキー。
     */
    lookup_key?: string | null;
    /**
     * 価格の通貨。現在は `jpy` のみサポートしています。
     */
    currency?: Currency;
    /**
     * Product
     * この価格が紐付く商品のID。
     */
    product?: string;
    /**
     * Unit Amount
     * 価格の単価。0以上の整数となります。
     */
    unit_amount?: number;
    /**
     * Created At
     * 支払い方法作成時の日時 (UTC, ISO 8601 形式)
     */
    created_at?: string;
    /**
     * Updated At
     * 支払い方法更新時の日時 (UTC, ISO 8601 形式)
     */
    updated_at?: string;
};

/**
 * PriceListResponse
 */
export type PriceListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<PriceDetailsResponse>;
};

/**
 * PriceType
 */
export type PriceType = 'one_time';

/**
 * PriceUpdateRequest
 */
export type PriceUpdateRequest = {
    /**
     * Nickname
     * 価格の名称。PAY.JP のダッシュボードで識別するためのもので、顧客には表示されません。
     */
    nickname?: string;
    /**
     * Lookup Key
     * この価格を検索するためのキー。
     */
    lookup_key?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Active
     * 価格が有効かどうか。デフォルトは `true`。
     */
    active?: boolean;
};

/**
 * ProductCreateRequest
 */
export type ProductCreateRequest = {
    /**
     * Default Price
     * この商品のデフォルト価格である価格オブジェクトのID。
     */
    default_price?: string;
    /**
     * Description
     * Checkoutなどで顧客に表示される商品説明。
     */
    description?: string;
    /**
     * Unit Label
     * この製品の単位を表すラベル。設定すると、Checkoutや請求書などに表示されます。（例：「個」、「ライセンス」、「時間」、「回」など）
     */
    unit_label?: string;
    /**
     * Url
     * この製品の公開されているウェブページのURL。
     */
    url?: string;
    /**
     * Id
     * 商品ID
     */
    id?: string;
    /**
     * Name
     * Checkoutなどで顧客に表示される商品名。
     */
    name: string;
    /**
     * Active
     * 商品が購入可能かどうか。デフォルトは `true`。
     */
    active?: boolean;
};

/**
 * ProductDeletedResponse
 */
export type ProductDeletedResponseReadable = {
    /**
     * Id
     * 商品ID
     */
    id: string;
    /**
     * Object
     */
    object?: 'product';
    /**
     * Deleted
     * 削除されたかどうか
     */
    readonly deleted: boolean;
};

/**
 * ProductDeletedResponse
 */
export type ProductDeletedResponseWritable = {
    /**
     * Id
     * 商品ID
     */
    id: string;
    /**
     * Object
     */
    object?: 'product';
};

/**
 * ProductDetailsResponse
 */
export type ProductDetailsResponse = {
    /**
     * Id
     * 商品ID
     */
    id: string;
    /**
     * Object
     */
    object?: 'product';
    /**
     * Name
     * Checkoutなどで顧客に表示される商品名。
     */
    name: string;
    /**
     * Active
     * 商品が購入可能かどうか。デフォルトは `true`。
     */
    active: boolean;
    /**
     * Default Price
     * この商品のデフォルト価格である価格オブジェクトのID。
     */
    default_price: string | null;
    /**
     * Description
     * Checkoutなどで顧客に表示される商品説明。
     */
    description: string | null;
    /**
     * Unit Label
     * この製品の単位を表すラベル。設定すると、Checkoutや請求書などに表示されます。（例：「個」、「ライセンス」、「時間」、「回」など）
     */
    unit_label: string | null;
    /**
     * Url
     * この製品の公開されているウェブページのURL。
     */
    url: string | null;
};

/**
 * ProductListResponse
 */
export type ProductListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<ProductDetailsResponse>;
};

/**
 * ProductUpdateRequest
 */
export type ProductUpdateRequest = {
    /**
     * Default Price
     * この商品のデフォルト価格である価格オブジェクトのID。
     */
    default_price?: string;
    /**
     * Description
     * Checkoutなどで顧客に表示される商品説明。
     */
    description?: string;
    /**
     * Unit Label
     * この製品の単位を表すラベル。設定すると、Checkoutや請求書などに表示されます。（例：「個」、「ライセンス」、「時間」、「回」など）
     */
    unit_label?: string;
    /**
     * Url
     * この製品の公開されているウェブページのURL。
     */
    url?: string;
    /**
     * Name
     * Checkoutなどで顧客に表示される商品名。
     */
    name?: string;
    /**
     * Active
     * 商品が購入可能かどうか。デフォルトは `true`。
     */
    active?: boolean;
};

/**
 * RefundCreateRequest
 */
export type RefundCreateRequest = {
    /**
     * Payment Intent
     * 返金対象となる PaymentIntent の ID
     */
    payment_intent: string;
    /**
     * Amount
     * 返金金額
     */
    amount?: number;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * 返金理由
     *
     * | 指定できる値 |
     * |:---|
     * | **duplicate**: 重複した支払い |
     * | **fraudulent**: 不正な支払い |
     * | **requested_by_customer**: 顧客の要求 |
     */
    reason?: PaymentRefundReason;
};

/**
 * RefundListResponse
 */
export type RefundListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     * 支払いインテントリスト
     */
    data: Array<RefundResponse>;
};

/**
 * RefundResponse
 */
export type RefundResponse = {
    /**
     * Id
     * 返金対象となる PaymentIntent の ID
     */
    id: string;
    /**
     * Object
     */
    object?: 'refund';
    /**
     * Created At
     * 作成時の日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新時の日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Amount
     * 返金金額
     */
    amount: number;
    /**
     * 返金ステータス
     *
     * <a href="https://docs.pay.jp/v2/refunds#refund_status" target="_blank">返金ステータスの詳細についてはこちらを参照してください。</a>
     *
     * | 指定できる値 |
     * |:---|
     * | **succeeded**: 成功 |
     * | **failed**: 失敗 |
     * | **pending**: 保留中 |
     * | **canceled**: キャンセル |
     */
    status: PaymentRefundStatus;
    /**
     * Payment Intent
     * 返金対象となる PaymentIntent の ID
     */
    payment_intent: string;
    /**
     * 返金理由
     *
     * | 指定できる値 |
     * |:---|
     * | **duplicate**: 重複した支払い |
     * | **fraudulent**: 不正な支払い |
     * | **requested_by_customer**: 顧客の要求 |
     */
    reason: PaymentRefundReason | null;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * SetupIntentCancelRequest
 */
export type SetupIntentCancelRequest = {
    /**
     * Cancellation Reason
     * この SetupIntent のキャンセル理由。
     *
     * | 指定できる値 |
     * |:---|
     * | **abandoned**: 顧客が支払いを完了しなかった場合。 |
     * | **requested_by_customer**: 顧客がキャンセルを要求した場合。 |
     * | **duplicate**: 支払い方法が重複している場合。 |
     */
    cancellation_reason?: string;
};

/**
 * SetupIntentConfirmRequest
 */
export type SetupIntentConfirmRequest = {
    /**
     * Payment Method
     * この SetupIntent に紐付ける決済方法のID
     */
    payment_method?: string;
    /**
     * 支払い方法データ
     */
    payment_method_data?: PaymentMethodCreateRequest;
    /**
     * Payment Method Options
     * この SetupIntent の支払い方法の個別設定。
     */
    payment_method_options?: {
        [key: string]: unknown;
    };
    /**
     * Return Url
     * 顧客が支払いを完了後、あるいはキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。`confirm=true` の場合のみ指定できます。
     */
    return_url?: string;
    /**
     * Use Payjp Sdk
     * PAY.JP SDK を使用するかどうか
     */
    use_payjp_sdk?: boolean;
};

/**
 * SetupIntentCreateRequest
 */
export type SetupIntentCreateRequest = {
    /**
     * Confirm
     * SetupIntent をすぐに確定しようとする場合に `true` を設定します。このパラメーターのデフォルト値は `false` です。カードが登録済みの支払い方法である場合は、追加の認証が必要な場合に備えて `return_url` を指定できます。
     */
    confirm?: boolean;
    /**
     * Customer
     * この SetupIntent が属する顧客の ID。SetupIntent に PaymentMethod が設定されている場合、SetupIntent の設定が成功するとその PaymentMethod は顧客に紐付きます。別の顧客に紐付いている PaymentMethod をこの SetupIntent で使用することはできません。
     */
    customer?: string;
    /**
     * Description
     * 説明。顧客に表示されます。
     */
    description?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Payment Method
     * この SetupIntent に紐付ける決済方法のID
     */
    payment_method?: string;
    /**
     * 支払い方法データ
     */
    payment_method_data?: PaymentMethodCreateRequest;
    /**
     * Payment Method Options
     * この SetupIntent の支払い方法の個別設定。
     */
    payment_method_options?: {
        [key: string]: unknown;
    };
    /**
     * Payment Method Types
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * Return Url
     * 顧客が支払いを完了後、あるいはキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。`confirm=true` の場合のみ指定できます。
     */
    return_url?: string;
    /**
     * 支払い方法が今後どのように使用されるかを指定します。指定されていない場合、この値はデフォルトで `off_session` になります。
     *
     * | 指定できる値 |
     * |:---|
     * | **off_session**: 定期課金など、顧客がカートなどの決済フローにいるかどうか不明な場合は `off_session` を使用してください。 |
     * | **on_session**: 顧客がカートなどの決済フローにいる場合にのみ支払い方法を利用する場合は `on_session` を使用してください。 |
     */
    usage?: Usage;
};

/**
 * SetupIntentDataRequest
 */
export type SetupIntentDataRequest = {
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * SetupIntentListResponse
 */
export type SetupIntentListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<SetupIntentResponse>;
};

/**
 * SetupIntentResponse
 */
export type SetupIntentResponse = {
    /**
     * Id
     * ID
     */
    id: string;
    /**
     * Object
     */
    object?: 'setup_intent';
    /**
     * Created At
     * 作成日時 (UTC, ISO 8601 形式)
     */
    created_at: string;
    /**
     * Updated At
     * 更新日時 (UTC, ISO 8601 形式)
     */
    updated_at: string;
    /**
     * Livemode
     * 本番環境かどうか
     */
    livemode: boolean;
    /**
     * Client Secret
     * この SetupIntent のクライアントシークレットです。フロントエンドで公開鍵と合わせて使用し、SetupIntent の取得や支払い処理を行います。**この値はこの SetupIntent の支払いを行う顧客以外へ公開しないでください。
     */
    client_secret: string;
    /**
     * Customer
     * この SetupIntent が属する顧客の ID。SetupIntent に PaymentMethod が設定されている場合、SetupIntent の設定が成功するとその PaymentMethod は顧客に紐付きます。別の顧客に紐付いている PaymentMethod をこの SetupIntent で使用することはできません。
     */
    customer?: string | null;
    /**
     * Description
     * 説明。顧客に表示されます。
     */
    description?: string | null;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
    /**
     * Payment Method
     * この SetupIntent に紐付ける決済方法のID
     */
    payment_method?: string | null;
    /**
     * Payment Method Options
     * この SetupIntent の支払い方法の個別設定。
     */
    payment_method_options?: {
        [key: string]: unknown;
    } | null;
    /**
     * Payment Method Types
     * この SetupIntent で使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合、ダッシュボードで利用可能な状態にしている支払い方法が自動的に設定されます。
     */
    payment_method_types: Array<string>;
    /**
     * この SetupIntent のステータスです。<a href="https://docs.pay.jp/v2/setup_intents#status" target="_blank">ステータスの詳細についてはこちらをご覧ください。</a>
     *
     * | 値 |
     * |:---|
     * | **requires_payment_method**: 支払い方法が必要です。 |
     * | **requires_confirmation**: 確認が必要です。 |
     * | **requires_action**: 顧客のアクションが必要です。 |
     * | **processing**: 処理中です。 |
     * | **succeeded**: 成功しました。 |
     * | **canceled**: キャンセルされました。 |
     */
    status: SetupIntentStatus;
    /**
     * Next Action
     * 顧客が支払い設定を続けるために必要な対応がある場合、対応方法が記載されています。
     */
    next_action?: {
        [key: string]: unknown;
    } | null;
    /**
     * Return Url
     * 顧客が支払いを完了後、あるいはキャンセルした後にリダイレクトされるURL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。`confirm=true` の場合のみ指定できます。
     */
    return_url?: string | null;
};

/**
 * SetupIntentStatus
 */
export type SetupIntentStatus = 'canceled' | 'processing' | 'requires_action' | 'requires_confirmation' | 'requires_payment_method' | 'succeeded';

/**
 * SetupIntentUpdateRequest
 */
export type SetupIntentUpdateRequest = {
    /**
     * Customer
     * この SetupIntent が属する顧客の ID。SetupIntent に PaymentMethod が設定されている場合、SetupIntent の設定が成功するとその PaymentMethod は顧客に紐付きます。別の顧客に紐付いている PaymentMethod をこの SetupIntent で使用することはできません。
     */
    customer?: string;
    /**
     * Payment Method
     * この SetupIntent に紐付ける決済方法のID
     */
    payment_method?: string;
    /**
     * Payment Method Options
     * この SetupIntent の支払い方法の個別設定。
     */
    payment_method_options?: {
        [key: string]: unknown;
    };
    /**
     * Payment Method Types
     */
    payment_method_types?: Array<PaymentMethodTypes>;
    /**
     * Description
     * 説明。顧客に表示されます。
     */
    description?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * TaxRateCreateRequest
 */
export type TaxRateCreateRequest = {
    /**
     * Display Name
     * 表示名。顧客に表示されます。
     */
    display_name?: string;
    /**
     * Inclusive
     * 税込みかどうか。税込 = `true` 税抜 = `false`
     */
    inclusive?: boolean;
    /**
     * Percentage
     * 税率を % 単位で指定します（例： 10%の場合は「10」と入力）
     */
    percentage?: number;
    /**
     * Active
     * この税率が有効であるかどうか。無効にした場合でも、すでに設定されている定期課金などでは使用可能です。
     */
    active?: boolean;
    /**
     * 有効な2文字の <a href="https://ja.wikipedia.org/wiki/ISO_3166-1" target="_blank">ISO 国コード</a>
     */
    country?: Country;
    /**
     * Description
     * 説明。ダッシュボード内のみで表示され、顧客には表示されません。
     */
    description?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * TaxRateDetailsResponse
 */
export type TaxRateDetailsResponse = {
    /**
     * Object
     */
    object?: 'tax_rate';
    /**
     * Id
     * ID
     */
    id?: string;
    /**
     * Display Name
     * 表示名。顧客に表示されます。
     */
    display_name?: string;
    /**
     * Inclusive
     * 税込みかどうか。税込 = `true` 税抜 = `false`
     */
    inclusive?: boolean;
    /**
     * Percentage
     * 税率を % 単位で指定します（例： 10%の場合は「10」と入力）
     */
    percentage?: number;
    /**
     * Active
     * この税率が有効であるかどうか。無効にした場合でも、すでに設定されている定期課金などでは使用可能です。
     */
    active?: boolean;
    /**
     * 有効な2文字の <a href="https://ja.wikipedia.org/wiki/ISO_3166-1" target="_blank">ISO 国コード</a>
     */
    country?: Country | null;
    /**
     * Description
     * 説明。ダッシュボード内のみで表示され、顧客には表示されません。
     */
    description?: string | null;
    /**
     * 税金の種類。
     *
     * 現在は JCT のみ指定できます。
     *
     * | 指定できる値 |
     * |:---|
     * | **jct**: JCT (Japanese Consumption Tax, 日本の消費税) |
     */
    tax_type?: TaxType | null;
    /**
     * Metadata
     * メタデータ
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * TaxRateListResponse
 */
export type TaxRateListResponse = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Url
     * リスト取得URL
     */
    url: string;
    /**
     * Has More
     * 次のページがあるかどうか
     */
    has_more: boolean;
    /**
     * Data
     */
    data: Array<TaxRateDetailsResponse>;
};

/**
 * TaxRateUpdateRequest
 */
export type TaxRateUpdateRequest = {
    /**
     * Active
     * この税率が有効であるかどうか。無効にした場合でも、すでに設定されている定期課金などでは使用可能です。
     */
    active?: boolean;
    /**
     * 有効な2文字の <a href="https://ja.wikipedia.org/wiki/ISO_3166-1" target="_blank">ISO 国コード</a>
     */
    country?: Country;
    /**
     * Description
     * 説明。ダッシュボード内のみで表示され、顧客には表示されません。
     */
    description?: string;
    /**
     * Display Name
     * 表示名。顧客に表示されます。
     */
    display_name?: string;
    /**
     * Metadata
     * キーバリューの任意のデータを格納できます。<a href="https://docs.pay.jp/v2/metadata">詳細はメタデータのドキュメントを参照してください。</a>
     */
    metadata?: {
        [key: string]: string | number | boolean;
    };
};

/**
 * TaxType
 */
export type TaxType = 'jct';

/**
 * Usage
 */
export type Usage = 'on_session' | 'off_session';

export type GetAllPaymentMethodsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/payment_methods';
};

export type GetAllPaymentMethodsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllPaymentMethodsError = GetAllPaymentMethodsErrors[keyof GetAllPaymentMethodsErrors];

export type GetAllPaymentMethodsResponses = {
    /**
     * Successful Response
     */
    200: PaymentMethodListResponse;
};

export type GetAllPaymentMethodsResponse = GetAllPaymentMethodsResponses[keyof GetAllPaymentMethodsResponses];

export type CreatePaymentMethodData = {
    body: PaymentMethodCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/payment_methods';
};

export type CreatePaymentMethodErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreatePaymentMethodError = CreatePaymentMethodErrors[keyof CreatePaymentMethodErrors];

export type CreatePaymentMethodResponses = {
    /**
     * Successful Response
     */
    200: PaymentMethodResponse;
};

export type CreatePaymentMethodResponse = CreatePaymentMethodResponses[keyof CreatePaymentMethodResponses];

export type GetPaymentMethodData = {
    body?: never;
    path: {
        /**
         * Payment Method Id
         */
        payment_method_id: string;
    };
    query?: never;
    url: '/v2/payment_methods/{payment_method_id}';
};

export type GetPaymentMethodErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetPaymentMethodError = GetPaymentMethodErrors[keyof GetPaymentMethodErrors];

export type GetPaymentMethodResponses = {
    /**
     * Successful Response
     */
    200: PaymentMethodResponse;
};

export type GetPaymentMethodResponse = GetPaymentMethodResponses[keyof GetPaymentMethodResponses];

export type UpdatePaymentMethodData = {
    body: PaymentMethodCardUpdateRequest;
    path: {
        /**
         * Payment Method Id
         */
        payment_method_id: string;
    };
    query?: never;
    url: '/v2/payment_methods/{payment_method_id}';
};

export type UpdatePaymentMethodErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdatePaymentMethodError = UpdatePaymentMethodErrors[keyof UpdatePaymentMethodErrors];

export type UpdatePaymentMethodResponses = {
    /**
     * Successful Response
     */
    200: PaymentMethodResponse;
};

export type UpdatePaymentMethodResponse = UpdatePaymentMethodResponses[keyof UpdatePaymentMethodResponses];

export type GetAllProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/products';
};

export type GetAllProductsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllProductsError = GetAllProductsErrors[keyof GetAllProductsErrors];

export type GetAllProductsResponses = {
    /**
     * Successful Response
     */
    200: ProductListResponse;
};

export type GetAllProductsResponse = GetAllProductsResponses[keyof GetAllProductsResponses];

export type CreateProductData = {
    body: ProductCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/products';
};

export type CreateProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductDetailsResponse;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type DeleteProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/v2/products/{product_id}';
};

export type DeleteProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteProductError = DeleteProductErrors[keyof DeleteProductErrors];

export type DeleteProductResponses = {
    /**
     * Successful Response
     */
    200: ProductDeletedResponseReadable;
};

export type DeleteProductResponse = DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/v2/products/{product_id}';
};

export type GetProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * Successful Response
     */
    200: ProductDetailsResponse;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
    body: ProductUpdateRequest;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/v2/products/{product_id}';
};

export type UpdateProductErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductDetailsResponse;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type GetAllPricesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/prices';
};

export type GetAllPricesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllPricesError = GetAllPricesErrors[keyof GetAllPricesErrors];

export type GetAllPricesResponses = {
    /**
     * Successful Response
     */
    200: PriceListResponse;
};

export type GetAllPricesResponse = GetAllPricesResponses[keyof GetAllPricesResponses];

export type CreatePriceData = {
    body: PriceCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/prices';
};

export type CreatePriceErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreatePriceError = CreatePriceErrors[keyof CreatePriceErrors];

export type CreatePriceResponses = {
    /**
     * Successful Response
     */
    200: PriceDetailsResponse;
};

export type CreatePriceResponse = CreatePriceResponses[keyof CreatePriceResponses];

export type GetPriceData = {
    body?: never;
    path: {
        /**
         * Price Id
         */
        price_id: string;
    };
    query?: never;
    url: '/v2/prices/{price_id}';
};

export type GetPriceErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetPriceError = GetPriceErrors[keyof GetPriceErrors];

export type GetPriceResponses = {
    /**
     * Successful Response
     */
    200: PriceDetailsResponse;
};

export type GetPriceResponse = GetPriceResponses[keyof GetPriceResponses];

export type UpdatePriceData = {
    body: PriceUpdateRequest;
    path: {
        /**
         * Price Id
         */
        price_id: string;
    };
    query?: never;
    url: '/v2/prices/{price_id}';
};

export type UpdatePriceErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdatePriceError = UpdatePriceErrors[keyof UpdatePriceErrors];

export type UpdatePriceResponses = {
    /**
     * Successful Response
     */
    200: PriceDetailsResponse;
};

export type UpdatePriceResponse = UpdatePriceResponses[keyof UpdatePriceResponses];

export type RetrievePaymentIntentData = {
    body?: never;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}';
};

export type RetrievePaymentIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RetrievePaymentIntentError = RetrievePaymentIntentErrors[keyof RetrievePaymentIntentErrors];

export type RetrievePaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type RetrievePaymentIntentResponse = RetrievePaymentIntentResponses[keyof RetrievePaymentIntentResponses];

export type UpdatePaymentIntentData = {
    body: PaymentIntentUpdateRequest;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}';
};

export type UpdatePaymentIntentErrors = {
    /**
     * Invalid Status
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdatePaymentIntentError = UpdatePaymentIntentErrors[keyof UpdatePaymentIntentErrors];

export type UpdatePaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type UpdatePaymentIntentResponse = UpdatePaymentIntentResponses[keyof UpdatePaymentIntentResponses];

export type GetAllPaymentIntentData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/payment_intents';
};

export type GetAllPaymentIntentErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllPaymentIntentError = GetAllPaymentIntentErrors[keyof GetAllPaymentIntentErrors];

export type GetAllPaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentListResponse;
};

export type GetAllPaymentIntentResponse = GetAllPaymentIntentResponses[keyof GetAllPaymentIntentResponses];

export type CreatePaymentIntentData = {
    body: PaymentIntentCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/payment_intents';
};

export type CreatePaymentIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreatePaymentIntentError = CreatePaymentIntentErrors[keyof CreatePaymentIntentErrors];

export type CreatePaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type CreatePaymentIntentResponse = CreatePaymentIntentResponses[keyof CreatePaymentIntentResponses];

export type CancelPaymentIntentData = {
    /**
     * Params
     */
    body?: PaymentIntentCancelRequest | null;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}/cancel';
};

export type CancelPaymentIntentErrors = {
    /**
     * Invalid Status
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CancelPaymentIntentError = CancelPaymentIntentErrors[keyof CancelPaymentIntentErrors];

export type CancelPaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type CancelPaymentIntentResponse = CancelPaymentIntentResponses[keyof CancelPaymentIntentResponses];

export type CapturePaymentIntentData = {
    /**
     * Params
     */
    body?: PaymentIntentCaptureRequest | null;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}/capture';
};

export type CapturePaymentIntentErrors = {
    /**
     * Invalid Status
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CapturePaymentIntentError = CapturePaymentIntentErrors[keyof CapturePaymentIntentErrors];

export type CapturePaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type CapturePaymentIntentResponse = CapturePaymentIntentResponses[keyof CapturePaymentIntentResponses];

export type ConfirmPaymentIntentData = {
    /**
     * Params
     */
    body?: PaymentIntentConfirmRequest | null;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}/confirm';
};

export type ConfirmPaymentIntentErrors = {
    /**
     * Invalid Status<br>Missing Payment Method
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ConfirmPaymentIntentError = ConfirmPaymentIntentErrors[keyof ConfirmPaymentIntentErrors];

export type ConfirmPaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type ConfirmPaymentIntentResponse = ConfirmPaymentIntentResponses[keyof ConfirmPaymentIntentResponses];

export type IncrementAuthorizationPaymentIntentData = {
    body: PaymentIntentIncrementAuthorizationRequest;
    path: {
        /**
         * Payment Intent Id
         */
        payment_intent_id: string;
    };
    query?: never;
    url: '/v2/payment_intents/{payment_intent_id}/increment_authorization';
};

export type IncrementAuthorizationPaymentIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type IncrementAuthorizationPaymentIntentError = IncrementAuthorizationPaymentIntentErrors[keyof IncrementAuthorizationPaymentIntentErrors];

export type IncrementAuthorizationPaymentIntentResponses = {
    /**
     * Successful Response
     */
    200: PaymentIntentResponse;
};

export type IncrementAuthorizationPaymentIntentResponse = IncrementAuthorizationPaymentIntentResponses[keyof IncrementAuthorizationPaymentIntentResponses];

export type RetrieveRefundData = {
    body?: never;
    path: {
        /**
         * Refund Id
         */
        refund_id: string;
    };
    query?: never;
    url: '/v2/refunds/{refund_id}';
};

export type RetrieveRefundErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RetrieveRefundError = RetrieveRefundErrors[keyof RetrieveRefundErrors];

export type RetrieveRefundResponses = {
    /**
     * Successful Response
     */
    200: RefundResponse;
};

export type RetrieveRefundResponse = RetrieveRefundResponses[keyof RetrieveRefundResponses];

export type UpdateRefundData = {
    body: PaymentRefundUpdateRequest;
    path: {
        /**
         * Refund Id
         */
        refund_id: string;
    };
    query?: never;
    url: '/v2/refunds/{refund_id}';
};

export type UpdateRefundErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateRefundError = UpdateRefundErrors[keyof UpdateRefundErrors];

export type UpdateRefundResponses = {
    /**
     * Successful Response
     */
    200: RefundResponse;
};

export type UpdateRefundResponse = UpdateRefundResponses[keyof UpdateRefundResponses];

export type GetAllRefundsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/refunds';
};

export type GetAllRefundsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllRefundsError = GetAllRefundsErrors[keyof GetAllRefundsErrors];

export type GetAllRefundsResponses = {
    /**
     * Successful Response
     */
    200: RefundListResponse;
};

export type GetAllRefundsResponse = GetAllRefundsResponses[keyof GetAllRefundsResponses];

export type CreateRefundData = {
    body: RefundCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/refunds';
};

export type CreateRefundErrors = {
    /**
     * Invalid Status<br>Already Refunded<br>Refund Exceeds Payment
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateRefundError = CreateRefundErrors[keyof CreateRefundErrors];

export type CreateRefundResponses = {
    /**
     * Successful Response
     */
    200: RefundResponse;
};

export type CreateRefundResponse = CreateRefundResponses[keyof CreateRefundResponses];

export type CancelRefundData = {
    body?: never;
    path: {
        /**
         * Refund Id
         */
        refund_id: string;
    };
    query?: never;
    url: '/v2/refunds/{refund_id}/cancel';
};

export type CancelRefundErrors = {
    /**
     * Invalid Status
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CancelRefundError = CancelRefundErrors[keyof CancelRefundErrors];

export type CancelRefundResponses = {
    /**
     * Successful Response
     */
    200: RefundResponse;
};

export type CancelRefundResponse = CancelRefundResponses[keyof CancelRefundResponses];

export type RetrieveSetupIntentData = {
    body?: never;
    path: {
        /**
         * Setup Intent Id
         */
        setup_intent_id: string;
    };
    query?: never;
    url: '/v2/setup_intents/{setup_intent_id}';
};

export type RetrieveSetupIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type RetrieveSetupIntentError = RetrieveSetupIntentErrors[keyof RetrieveSetupIntentErrors];

export type RetrieveSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentResponse;
};

export type RetrieveSetupIntentResponse = RetrieveSetupIntentResponses[keyof RetrieveSetupIntentResponses];

export type UpdateSetupIntentData = {
    body: SetupIntentUpdateRequest;
    path: {
        /**
         * Setup Intent Id
         */
        setup_intent_id: string;
    };
    query?: never;
    url: '/v2/setup_intents/{setup_intent_id}';
};

export type UpdateSetupIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateSetupIntentError = UpdateSetupIntentErrors[keyof UpdateSetupIntentErrors];

export type UpdateSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentResponse;
};

export type UpdateSetupIntentResponse = UpdateSetupIntentResponses[keyof UpdateSetupIntentResponses];

export type GetAllSetupIntentData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/setup_intents';
};

export type GetAllSetupIntentErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllSetupIntentError = GetAllSetupIntentErrors[keyof GetAllSetupIntentErrors];

export type GetAllSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentListResponse;
};

export type GetAllSetupIntentResponse = GetAllSetupIntentResponses[keyof GetAllSetupIntentResponses];

export type CreateSetupIntentData = {
    /**
     * Params
     */
    body?: SetupIntentCreateRequest | null;
    path?: never;
    query?: never;
    url: '/v2/setup_intents';
};

export type CreateSetupIntentErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateSetupIntentError = CreateSetupIntentErrors[keyof CreateSetupIntentErrors];

export type CreateSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentResponse;
};

export type CreateSetupIntentResponse = CreateSetupIntentResponses[keyof CreateSetupIntentResponses];

export type CancelSetupIntentData = {
    /**
     * Params
     */
    body?: SetupIntentCancelRequest | null;
    path: {
        /**
         * Setup Intent Id
         */
        setup_intent_id: string;
    };
    query?: never;
    url: '/v2/setup_intents/{setup_intent_id}/cancel';
};

export type CancelSetupIntentErrors = {
    /**
     * Invalid Status
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CancelSetupIntentError = CancelSetupIntentErrors[keyof CancelSetupIntentErrors];

export type CancelSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentResponse;
};

export type CancelSetupIntentResponse = CancelSetupIntentResponses[keyof CancelSetupIntentResponses];

export type ConfirmSetupIntentData = {
    /**
     * Params
     */
    body?: SetupIntentConfirmRequest | null;
    path: {
        /**
         * Setup Intent Id
         */
        setup_intent_id: string;
    };
    query?: never;
    url: '/v2/setup_intents/{setup_intent_id}/confirm';
};

export type ConfirmSetupIntentErrors = {
    /**
     * Invalid Status<br>Missing Payment Method
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type ConfirmSetupIntentError = ConfirmSetupIntentErrors[keyof ConfirmSetupIntentErrors];

export type ConfirmSetupIntentResponses = {
    /**
     * Successful Response
     */
    200: SetupIntentResponse;
};

export type ConfirmSetupIntentResponse = ConfirmSetupIntentResponses[keyof ConfirmSetupIntentResponses];

export type GetAllCheckoutSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/checkout/sessions';
};

export type GetAllCheckoutSessionsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllCheckoutSessionsError = GetAllCheckoutSessionsErrors[keyof GetAllCheckoutSessionsErrors];

export type GetAllCheckoutSessionsResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionListResponse;
};

export type GetAllCheckoutSessionsResponse = GetAllCheckoutSessionsResponses[keyof GetAllCheckoutSessionsResponses];

export type CreateCheckoutSessionData = {
    body: CheckoutSessionCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/checkout/sessions';
};

export type CreateCheckoutSessionErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateCheckoutSessionError = CreateCheckoutSessionErrors[keyof CreateCheckoutSessionErrors];

export type CreateCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionDetailsResponse;
};

export type CreateCheckoutSessionResponse = CreateCheckoutSessionResponses[keyof CreateCheckoutSessionResponses];

export type GetCheckoutSessionData = {
    body?: never;
    path: {
        /**
         * Checkout Session Id
         */
        checkout_session_id: string;
    };
    query?: {
        /**
         * Expand
         * レスポンス返却時に展開したいオブジェクト名。指定したオブジェクトを同時に取得し、レスポンスに乗せて返却します。
         */
        expand?: Array<'line_items' | 'customer'> | null;
    };
    url: '/v2/checkout/sessions/{checkout_session_id}';
};

export type GetCheckoutSessionErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetCheckoutSessionError = GetCheckoutSessionErrors[keyof GetCheckoutSessionErrors];

export type GetCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionDetailsResponse;
};

export type GetCheckoutSessionResponse = GetCheckoutSessionResponses[keyof GetCheckoutSessionResponses];

export type UpdateCheckoutSessionData = {
    body: CheckoutSessionUpdateRequest;
    path: {
        /**
         * Checkout Session Id
         */
        checkout_session_id: string;
    };
    query?: never;
    url: '/v2/checkout/sessions/{checkout_session_id}';
};

export type UpdateCheckoutSessionErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateCheckoutSessionError = UpdateCheckoutSessionErrors[keyof UpdateCheckoutSessionErrors];

export type UpdateCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionDetailsResponse;
};

export type UpdateCheckoutSessionResponse = UpdateCheckoutSessionResponses[keyof UpdateCheckoutSessionResponses];

export type GetAllTaxRatesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/tax_rates';
};

export type GetAllTaxRatesErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllTaxRatesError = GetAllTaxRatesErrors[keyof GetAllTaxRatesErrors];

export type GetAllTaxRatesResponses = {
    /**
     * Successful Response
     */
    200: TaxRateListResponse;
};

export type GetAllTaxRatesResponse = GetAllTaxRatesResponses[keyof GetAllTaxRatesResponses];

export type CreateTaxRateData = {
    body: TaxRateCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/tax_rates';
};

export type CreateTaxRateErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateTaxRateError = CreateTaxRateErrors[keyof CreateTaxRateErrors];

export type CreateTaxRateResponses = {
    /**
     * Successful Response
     */
    200: TaxRateDetailsResponse;
};

export type CreateTaxRateResponse = CreateTaxRateResponses[keyof CreateTaxRateResponses];

export type GetTaxRateData = {
    body?: never;
    path: {
        /**
         * Tax Rate Id
         */
        tax_rate_id: string;
    };
    query?: never;
    url: '/v2/tax_rates/{tax_rate_id}';
};

export type GetTaxRateErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetTaxRateError = GetTaxRateErrors[keyof GetTaxRateErrors];

export type GetTaxRateResponses = {
    /**
     * Successful Response
     */
    200: TaxRateDetailsResponse;
};

export type GetTaxRateResponse = GetTaxRateResponses[keyof GetTaxRateResponses];

export type UpdateTaxRateData = {
    body: TaxRateUpdateRequest;
    path: {
        /**
         * Tax Rate Id
         */
        tax_rate_id: string;
    };
    query?: never;
    url: '/v2/tax_rates/{tax_rate_id}';
};

export type UpdateTaxRateErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateTaxRateError = UpdateTaxRateErrors[keyof UpdateTaxRateErrors];

export type UpdateTaxRateResponses = {
    /**
     * Successful Response
     */
    200: TaxRateDetailsResponse;
};

export type UpdateTaxRateResponse = UpdateTaxRateResponses[keyof UpdateTaxRateResponses];

export type GetAllCustomersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
    };
    url: '/v2/customers';
};

export type GetAllCustomersErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllCustomersError = GetAllCustomersErrors[keyof GetAllCustomersErrors];

export type GetAllCustomersResponses = {
    /**
     * Successful Response
     */
    200: CustomerListResponse;
};

export type GetAllCustomersResponse = GetAllCustomersResponses[keyof GetAllCustomersResponses];

export type CreateCustomerData = {
    body: CustomerCreateRequest;
    path?: never;
    query?: never;
    url: '/v2/customers';
};

export type CreateCustomerErrors = {
    /**
     * Already Exists ID
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type CreateCustomerError = CreateCustomerErrors[keyof CreateCustomerErrors];

export type CreateCustomerResponses = {
    /**
     * Successful Response
     */
    200: CustomerResponse;
};

export type CreateCustomerResponse = CreateCustomerResponses[keyof CreateCustomerResponses];

export type DeleteCustomerData = {
    body?: never;
    path: {
        /**
         * Customer Id
         */
        customer_id: string;
    };
    query?: never;
    url: '/v2/customers/{customer_id}';
};

export type DeleteCustomerErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type DeleteCustomerError = DeleteCustomerErrors[keyof DeleteCustomerErrors];

export type DeleteCustomerResponses = {
    /**
     * Successful Response
     */
    200: CustomerResponse;
};

export type DeleteCustomerResponse = DeleteCustomerResponses[keyof DeleteCustomerResponses];

export type GetCustomerData = {
    body?: never;
    path: {
        /**
         * Customer Id
         */
        customer_id: string;
    };
    query?: never;
    url: '/v2/customers/{customer_id}';
};

export type GetCustomerErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetCustomerError = GetCustomerErrors[keyof GetCustomerErrors];

export type GetCustomerResponses = {
    /**
     * Successful Response
     */
    200: CustomerResponse;
};

export type GetCustomerResponse = GetCustomerResponses[keyof GetCustomerResponses];

export type UpdateCustomerData = {
    body: CustomerUpdateRequest;
    path: {
        /**
         * Customer Id
         */
        customer_id: string;
    };
    query?: never;
    url: '/v2/customers/{customer_id}';
};

export type UpdateCustomerErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type UpdateCustomerError = UpdateCustomerErrors[keyof UpdateCustomerErrors];

export type UpdateCustomerResponses = {
    /**
     * Successful Response
     */
    200: CustomerResponse;
};

export type UpdateCustomerResponse = UpdateCustomerResponses[keyof UpdateCustomerResponses];

export type GetAllEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Since
         * 指定した日付以降のデータを取得
         */
        since?: string | null;
        /**
         * Until
         * 指定した日付以前のデータを取得
         */
        until?: string | null;
        /**
         * Limit
         * 取得するデータの最大件数
         */
        limit?: number;
        /**
         * Offset
         * データ取得を行う開始位置
         */
        offset?: number;
        /**
         * Resource Id
         * 取得するeventに紐づくAPIリソースのID (e.g. customer.id)
         */
        resource_id?: string | null;
        /**
         * Object
         * 取得するeventに紐づくAPIリソースのobject。値はリソース名(e.g. customer, payment_intent)
         */
        object?: string | null;
        /**
         * Type
         * 取得するeventのtype
         */
        type?: string | null;
    };
    url: '/v2/events';
};

export type GetAllEventsErrors = {
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetAllEventsError = GetAllEventsErrors[keyof GetAllEventsErrors];

export type GetAllEventsResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type GetAllEventsResponse = GetAllEventsResponses[keyof GetAllEventsResponses];

export type GetEventData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/v2/events/{event_id}';
};

export type GetEventErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: ErrorResponse;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};